### ISSUE TITLE
Notifications missed!

### ISSUE THREAD

**Issue by FedeL16** [gmlupatelli/blueprints_repo#16]
hello, I have a problem, because notifications of unvailability entities are not received on my smartphone via telegram or mobile app using {{entities}} or {{ entities|replace('_', ' ') }}, how can I do to obtain my entities in notifications?

thank you

**Comment by gmlupatelli** [comment]
Here is an example of my configuration using e-mail notifications with a working "message":
```
service: notify.home_email_gustavo
data:
  title: Unavailable Entities
  message: "Here is a list of unavailable entities in your home: {{entities}}"
```
