### ISSUE TITLE
(Feature) Add ability to use regex to exclude entities

### ISSUE THREAD

**Issue by melyux** [gmlupatelli/blueprints_repo#6]
I also implemented this.

Add this to the `blueprint` → `input`:
```
    exclude_regex:
      name: Excluded Entities (Regex)
      description: Entities to exclude from detection, using regex on entity IDs. One line per expression.
      default: ""
      selector:
        text:
          multiline: true
```

Add this to `variables`:
```
  exclude_regex: !input 'exclude_regex'
```

Replace `variables` → `entities` with this:
```
  entities: >-
    {% set result = namespace(entities=[]) %}
    {% for state in states %}
      {% if state.state == 'unavailable' and
          (not exclude.entity_id is defined or not state.entity_id in exclude.entity_id) and
          (not exclude_regex.strip() or not state.entity_id is match(exclude_regex | replace('\n', '|'))) %}
        {% set result.entities = result.entities + [state.name] %}
      {% endif %}
    {% endfor %}
    {{ result.entities | sort | join('\n') }}
```

New behaviors besides: this will also join entities with newlines instead of comma and space (#4) and sort them alphabetically for display.
